[workspace]
members = [
  "tauri",
  "tauri-api",
  "tauri-macros",
  "tauri-utils",

  # examples
  #"examples/api/src-tauri",
  "examples/helloworld/src-tauri",
  "examples/multiwindow/src-tauri",
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "z"
