[workspace]
members = [
  "tauri",
  "tauri-api",
  "tauri-utils",

  # examples
  "examples/communication/src-tauri",
  "examples/multiwindow/src-tauri"
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "z"
