[package]
name = "multiwindow"
version = "0.1.0"
description = "An example Tauri Multi-Window Application"
edition = "2018"

[build-dependencies]
tauri = { path = "../../../tauri", features =[ "build" ]}

[dependencies]
tauri = { path = "../../../tauri", features =[ "api-all" ]}

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
default = [ "tauri/embedded-server" ]
